[package]
name = "clowd_capture_wgpu"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
image = "0.25"
euclid = "0.22"
windows = { version = "0.62", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_System_SystemInformation",
] }
winit = "0.30"
wgpu = "29.0"
rayon = "1.11"
log = "0.4"
num = "0.4"
pollster = "0.4"
bytemuck = "1"
simplelog = "0.12"
