// ******************************************************************************
// This code was generated by a tool. 
// Any changes made manually will be lost the next time this code is regenerated
// with the exception of AssemblyVersion, this number is read and incremented
// according to the build. 
// ******************************************************************************

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Resources;
using System.Windows;

// General Information
[assembly: AssemblyTitle("Clowd")]
[assembly: AssemblyDescription("File sharing app")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Caesa Consulting Ltd.")]
[assembly: AssemblyProduct("Clowd")]
[assembly: AssemblyCopyright("Copyright © Caesa Consulting Ltd. 2014-2021")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Version Information
// Revision and build numbers are auto-incrimented.
[assembly: AssemblyVersion("2.4.47.2056")]
[assembly: AssemblyFileVersion("2.4.47.2056")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]

// Assembly Information
[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]
[assembly: ComVisible(false)]

