<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <TieredPgo>true</TieredPgo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="11.3.13" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Clowd.Drawing\Clowd.Drawing.csproj" />
  </ItemGroup>
</Project>
