using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using Avalonia.Platform;
using Clowd.VideoSDK.Composition;
using SkiaSharp;

namespace Clowd.UI.VideoEditor.Inspector
{
    /// <summary>
    /// The pre-rendered loop sheets the background STYLE tiles play, decoded once and kept for the
    /// life of the process. One sheet per animated style, laid out by
    /// <see cref="BackgroundTileSheet"/> and generated by <c>tools/background-tiles</c> from the
    /// very renderer the canvas draws with.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Why the sheets exist at all</b> is measured cost, not tidiness: an animated wallpaper
    /// cannot use <c>SvgBackgroundScene</c>'s recorded picture, so every tile frame walks the SVG
    /// tree, and Breathing Field's <c>feGaussianBlur</c> costs a 480px CPU raster and blur per
    /// frame, 9.1 ms in a 34px swatch, on the same render thread that composes the video preview,
    /// where Moving Blob and Moving Corners cost 0.015 ms. Playing a sheet is one textured quad
    /// out of one texture the GPU keeps, so the three tiles together stop registering.
    /// </para>
    /// <para>
    /// <b>The decode is off the UI thread</b>, and the caller gets null until it lands. Decoding
    /// three WebP sheets (about 1.1 megapixels each) synchronously on the first paint of the
    /// BACKGROUND section would trade a permanent per-frame cost for a visible one-off stall,
    /// which is only half a fix. Nothing has to be signalled when a sheet arrives: a tile only
    /// asks while it is animating, and an animating tile is being invalidated by
    /// <c>BackgroundStylePreview.TileClock</c> anyway, so the next tick picks the sheet up. Until
    /// then the tile draws the wallpaper live, which is exactly the behaviour this replaces and
    /// therefore a safe thing to fall back to.
    /// </para>
    /// <para>
    /// A style whose sheet is missing or unreadable caches null and draws live forever, so a
    /// build with no assets folder is a slower picker rather than a blank one, the same graceful
    /// nothing the tile draws on a non-Skia backend.
    /// </para>
    /// </remarks>
    public static class BackgroundTileLoop
    {
        /// <summary>The Avalonia resource URI a style's sheet is embedded at. Public because the
        /// asset-integrity test addresses the sheets the way the app does rather than by guessing
        /// at a path on disk.</summary>
        public static Uri UriOf(string styleId)
            => new Uri($"avares://Clowd.Ui/Assets/{BackgroundTileSheet.AssetFolder}/{BackgroundTileSheet.FileNameOf(styleId)}");

        private sealed class Entry
        {
            /// <summary>The decoded sheet, or null while the decode is in flight or after it
            /// failed. <see cref="Bitmap"/> owns the pixels the image shares, so the two are kept
            /// together and neither is ever disposed.</summary>
            public SKImage Image;

            public SKBitmap Bitmap;
        }

        private static readonly object Sync = new object();
        private static readonly Dictionary<string, Entry> Sheets = new Dictionary<string, Entry>(StringComparer.OrdinalIgnoreCase);

        /// <summary>
        /// The sheet for a style, starting the decode on the first ask and returning null until it
        /// is ready (and forever, for a style with no sheet). Safe to call from any thread; call it
        /// from the UI thread rather than from inside a custom draw operation, so that the render
        /// thread only ever receives an image that is already decoded.
        /// </summary>
        public static SKImage Get(string styleId)
        {
            if (string.IsNullOrEmpty(styleId))
                return null;

            lock (Sync)
            {
                if (Sheets.TryGetValue(styleId, out var entry))
                    return entry.Image;

                Sheets[styleId] = new Entry();
            }

            Task.Run(() => Decode(styleId));
            return null;
        }

        private static void Decode(string styleId)
        {
            SKBitmap bitmap = null;
            SKImage image = null;
            try
            {
                var uri = UriOf(styleId);
                if (AssetLoader.Exists(uri))
                {
                    using var stream = AssetLoader.Open(uri);
                    // Through a MemoryStream because SKBitmap.Decode wants to seek and the asset
                    // loader's stream makes no promise that it can; the sheets are around 50 KB.
                    using var buffer = new MemoryStream();
                    stream.CopyTo(buffer);
                    buffer.Position = 0;
                    bitmap = SKBitmap.Decode(buffer);
                }

                if (bitmap != null)
                {
                    // Immutable, so the image shares the bitmap's pixels rather than copying them
                    // (the same trade SvgGroup.DrawBlurred makes with its blurred raster), and so
                    // Skia is free to keep one uploaded texture for it in the GPU resource cache
                    // across every frame every tile draws.
                    bitmap.SetImmutable();
                    image = SKImage.FromBitmap(bitmap);
                }
            }
            catch (Exception ex)
            {
                // A missing or corrupt sheet is a slower tile, not a broken panel.
                Debug.WriteLine("BackgroundTileLoop: could not load the sheet for " + styleId + ": " + ex.Message);
                image = null;
            }

            if (image == null)
                bitmap?.Dispose();

            lock (Sync)
            {
                var entry = Sheets[styleId];
                entry.Bitmap = image == null ? null : bitmap;
                entry.Image = image;
            }
        }
    }
}
