using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Clowd.Server.Config
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    public sealed partial class ClowdConfigSection : System.Configuration.ConfigurationSection
    {

        [System.Configuration.ConfigurationPropertyAttribute("httpPort", IsRequired = true)]
        public int HttpPort
        {
            get
            {
                return ((int)(this["httpPort"]));
            }
            set
            {
                this["httpPort"] = value;
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("servicePort", IsRequired = true)]
        public int ServicePort
        {
            get
            {
                return ((int)(this["servicePort"]));
            }
            set
            {
                this["servicePort"] = value;
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("streamingPort", IsRequired = true)]
        public int StreamingPort
        {
            get
            {
                return ((int)(this["streamingPort"]));
            }
            set
            {
                this["streamingPort"] = value;
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("externalEndpoint", IsRequired = true)]
        public string ExternalEndpoint
        {
            get
            {
                return ((string)(this["externalEndpoint"]));
            }
            set
            {
                this["externalEndpoint"] = value;
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("listenIP", IsRequired = true)]
        public string ListenIP
        {
            get
            {
                return ((string)(this["listenIP"]));
            }
            set
            {
                this["listenIP"] = value;
            }
        }
    }
}
