using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Windows.Input;
using Avalonia.Controls;
using Avalonia.Platform;
using Clowd.UI.Helpers;
using Clowd.Util;

namespace Clowd.UI.Pages
{
    // Data model for Assets/credits.json. That file is generated by tools/gen-credits.sh —
    // re-run the script to refresh the list; do not edit the JSON (or this list) by hand.
    public class CreditsData
    {
        [JsonPropertyName("sections")] public List<CreditsSection> Sections { get; set; } = new();
    }

    public class CreditsSection
    {
        [JsonPropertyName("title")] public string Title { get; set; }
        [JsonPropertyName("items")] public List<CreditsItem> Items { get; set; } = new();
    }

    public class CreditsItem
    {
        [JsonPropertyName("name")] public string Name { get; set; }
        [JsonPropertyName("version")] public string Version { get; set; }
        [JsonPropertyName("license")] public string License { get; set; }
        [JsonPropertyName("url")] public string Url { get; set; }

        private ICommand _openCommand;

        // The whole row is a button bound to this command; it opens the project's repository.
        [JsonIgnore]
        public ICommand OpenCommand => _openCommand ??= new RelayCommand { Executed = _ => Open() };

        private void Open()
        {
            if (string.IsNullOrWhiteSpace(Url)) return;
            Process.Start(new ProcessStartInfo { FileName = Url, UseShellExecute = true });
        }
    }

    public class AboutPageViewModel : SimpleNotifyObject
    {
        public string ClowdVersion { get; set; }
        public List<CreditsSection> Sections { get; set; } = new();
    }

    public partial class AboutPage : UserControl
    {
        public AboutPage()
        {
            InitializeComponent();

            DataContext = new AboutPageViewModel
            {
                ClowdVersion = "Version " + GetCurrentVersion(),
                Sections = LoadCredits().Sections,
            };
        }

        private static CreditsData LoadCredits()
        {
            try
            {
                using var stream = AssetLoader.Open(new Uri("avares://Clowd.Ui/Assets/credits.json"));
                using var reader = new StreamReader(stream);
                return JsonSerializer.Deserialize(reader.ReadToEnd(), ClowdUiJsonContext.Default.CreditsData) ?? new CreditsData();
            }
            catch (Exception ex)
            {
                // The credits list is non-essential; a load failure must not break the About page.
                Debug.WriteLine($"Failed to load credits.json: {ex}");
                return new CreditsData();
            }
        }

        private static string GetCurrentVersion()
        {
            var assembly = typeof(AboutPage).Assembly;
            var informational = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
            if (!String.IsNullOrWhiteSpace(informational))
                return informational;

            return assembly.GetName().Version?.ToString() ?? "(dev)";
        }
    }
}
