<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Clowd.Drawing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Clowd.Drawing.Tests" />
    <InternalsVisibleTo Include="Clowd.Drawing.Benchmarks" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Clowd.Shared\Clowd.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Cursors\*.cur" />
  </ItemGroup>
</Project>
