<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Clowd.UI</RootNamespace>
    <ApplicationIcon>Assets\clowd-default.ico</ApplicationIcon>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
    <PackageReference Include="Semi.Avalonia" Version="11.3.7.3" />
    <PackageReference Include="Irihi.Ursa" Version="1.15.1" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.15.1" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.13" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SharpHook" Version="7.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Clowd.Drawing\Clowd.Drawing.csproj" />
    <ProjectReference Include="..\Clowd.Shared\Clowd.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
