[package]
name = "clowd_capture"
version = "0.0.0-local"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
image = { workspace = true }
euclid = { workspace = true }
windows = { workspace = true, features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_System_SystemInformation",
] }
clap = { workspace = true, features = ["derive"] }
rayon = { workspace = true }
num = { workspace = true }
bevy = { workspace = true, default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_color",
    "bevy_render",
    "bevy_winit",
    "bevy_window",
    "bevy_text",
    "bevy_asset",
    "bevy_sprite",
    "bevy_ui",
    "multi_threaded",
    "png",
    "shader_format_spirv",
    "spirv_shader_passthrough",
    "default_font",
] }
bevy_prototype_lyon = { workspace = true }
iyes_perf_ui = { workspace = true }
spin_sleep = { workspace = true }
raw-window-handle = { workspace = true }
resvg = { workspace = true }
rfd = { workspace = true }
arboard = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[target.'cfg(target_os="macos")'.dependencies]
xcap = { workspace = true }
mouse-rs = { workspace = true }

[build-dependencies]
winres = { workspace = true }
semver = { workspace = true }
