name: Build Clowd
on: 
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.301
      - name: "Install CSQ"
        run: dotnet tool install -g csq --version 3.0.210-g5f9f594
      - name: Build Clowd
        shell: pwsh
        run: .\build.ps1 -mode compile -keyId ${{ secrets.B2_KEY_ID }} -keySecret ${{ secrets.B2_KEY_SECRET }}
      - name: Upload Release to B2
        shell: pwsh
        run: .\build.ps1 -mode upload -keyId ${{ secrets.B2_KEY_ID }} -keySecret ${{ secrets.B2_KEY_SECRET }}
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          path: .\releases\*
          if-no-files-found: error
